-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.brand
(
    id SERIAL NOT NULL,
    name character varying ,
    CONSTRAINT brand_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cart
(
    cart_id SERIAL NOT NULL,
    user_id integer,
    CONSTRAINT cart_pkey PRIMARY KEY (cart_id)
);

CREATE TABLE IF NOT EXISTS public.cart_items
(
    cart_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity smallint DEFAULT 1,
    price integer,
    id SERIAL NOT NULL,
    CONSTRAINT cart_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    id SERIAL NOT NULL,
    name character varying(100)  NOT NULL,
    "typeID" smallint,
    "brandID" smallint,
    price integer,
    amount smallint,
    img character varying(100) ,
    description text ,
    CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.type
(
    id SERIAL NOT NULL,
    name character varying(25)  NOT NULL,
    CONSTRAINT type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id SERIAL NOT NULL,
    email character varying(40) NOT NULL,
    name character varying(15) ,
    surname character varying(30) ,
    role character varying(10)  NOT NULL DEFAULT 'Customer'::character varying,
    password character varying(100)  NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT email_unique UNIQUE (email)
);

ALTER TABLE IF EXISTS public.cart
    ADD CONSTRAINT "userIDinCart" FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id)
    REFERENCES public.cart (cart_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT "brandID" FOREIGN KEY ("brandID")
    REFERENCES public.brand (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT "typeID" FOREIGN KEY ("typeID")
    REFERENCES public.type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;