-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.brand
(
    id smallint NOT NULL DEFAULT nextval('brand_id_seq'::regclass),
    name character varying COLLATE pg_catalog."default",
    CONSTRAINT brand_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cart
(
    cart_id integer NOT NULL DEFAULT nextval('cart_cart_id_seq'::regclass),
    user_id integer,
    CONSTRAINT cart_pkey PRIMARY KEY (cart_id)
);

CREATE TABLE IF NOT EXISTS public.cart_items
(
    cart_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity smallint DEFAULT 1,
    price integer,
    id integer NOT NULL DEFAULT nextval('cart_items_id_seq'::regclass),
    CONSTRAINT cart_items_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    id integer NOT NULL DEFAULT nextval('product_id_seq'::regclass),
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "typeID" smallint,
    "brandID" smallint,
    price integer,
    amount smallint,
    img character varying(100) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT product_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.type
(
    id smallint NOT NULL DEFAULT nextval('type_id_seq'::regclass),
    name character varying(25) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT type_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id integer NOT NULL DEFAULT nextval('user_id_seq'::regclass),
    email character varying(40) COLLATE pg_catalog."default" NOT NULL,
    name character varying(15) COLLATE pg_catalog."default",
    surname character varying(30) COLLATE pg_catalog."default",
    role character varying(10) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Customer'::character varying,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id),
    CONSTRAINT email_unique UNIQUE (email)
);

ALTER TABLE IF EXISTS public.cart
    ADD CONSTRAINT "userIDinCart" FOREIGN KEY (user_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT cart_items_cart_id_fkey FOREIGN KEY (cart_id)
    REFERENCES public.cart (cart_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.cart_items
    ADD CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.product (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT "brandID" FOREIGN KEY ("brandID")
    REFERENCES public.brand (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT "typeID" FOREIGN KEY ("typeID")
    REFERENCES public.type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;